Add a method to extract the VIN from UAuthority
eclipse-uprotocol/up-java pull request #58
Opened 2023-12-11 23:14 UTC by neelam-kushwah

This commit addresses issue #56

2023-12-12 17:50 UTC, tamarafischer approved these changes

2023-12-13 20:52 UTC, stevenhartley requested changes
Need to address this problem differently

2023-12-13 20:52 UTC, stevenhartley commented on src/main/java/org/eclipse/uprotocol/uri/UuriUtils.java
> +                .map(parts -> parts[0].startsWith("vcu") ? parts[1] : parts[0]);
@neelam-kushwah we cannot put this code in the eclipse project, it is specific to GM's namespace for device/domain and not portable for other vendors that might use some other naming convention (they might only use VIN or not use VIN at all).

2024-01-08 22:01 UTC, stevenhartley requested changes
We cannot merge this as-is

2024-01-24 18:12 UTC, closed without merging

2024-01-24 18:12 UTC, stevenhartley commented
Closing the PR, it cannot be merged as is, please create a new one when ready